# This file is used to define the services that will be used in the application.
services:
  # mongo:
  #   image: mongo
  #   container_name: mongo_container
  #   volumes:
  #     - mongo_data:/data/db
  #   ports:
  #     - "27017:27017"
  # ✅ Removed the mongo service because you're using MongoDB Atlas instead of a local MongoDB container.

  server:
    build: ./server
    container_name: server_container
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb+srv://dinuthlahiru:dinuthlahiru@cluster0.3xgqo.mongodb.net/aitravel?retryWrites=true&w=majority
    
  client:
    build: ./ai-travel-planner
    container_name: client_container
    ports:
      - "5173:5173"
    depends_on:
      - server
    stdin_open: true
    tty: true
    volumes:
      - ./ai-travel-planner:/app
      - /ai-travel-planner/node_modules

volumes:
  mongo_data:
